export interface Antelope {
  license_year: number,
  district: string,
  residency: string,
  hunters: number,
  days: number,
  days_per_hunter: number,
  total_harvest: number,
  bucks: number,
  does: number,
  fawns: number,
  location: string,
  district_square_mileage: number,
  public_land_percentage: number,
  harvested_bucks_per_square_mile: number,
  harvested_does_per_square_mile: number,
  harvested_fawns_per_square_mile: number,
  total_harvest_per_square_mile: number,
}
