export interface Sheep {
  license_year: number,
  district: string,
  residency: string,
  hunters: number,
  days: number,
  days_per_hunter: number,
  total_harvest: number,
  rams: number,
  ewes: number,
  lambs: number,
  location: string,
  district_square_mileage: number,
  public_land_percentage: number,
  harvested_rams_per_square_mile: number,
  harvested_ewes_per_square_mile: number,
  harvested_lambs_per_square_mile: number,
  total_harvest_per_square_mile: number,
}
