export interface Elk {
  license_year?: number,
  hunting_district?: string,
  residency?: string,
  hunters?: number,
  days?: number,
  days_per_hunter?: number,
  total_harvest?: number,
  bulls?: number,
  cows?: number,
  calves?: number,
  bow?: number,
  rifle?: number,
  spike_bull_elk?: number,
  less_than_six_points?: number,
  six_or_more_points?: number,
  location?: string,
  district_square_mileage?: number,
  public_land_percentage?: number,
  diy_hunting_maps_hunt_success_rate_for_twenty_one?: number,
  harvested_bulls_per_square_mile?: number,
  harvested_cows_per_square_mile?: number,
  harvested_calves_per_square_mile?: number,
  harvested_spiked_bulls_per_square_mile?: number,
  harvested_six_or_more_point_bulls_per_square_mile?: number,
  total_harvest_per_square_mile?: number,
  six_or_more_points_percentage?: number,
}
