export interface Moose {
  license_year: number,
  district: string,
  residency: string,
  hunters: number,
  days: number,
  days_per_hunter: number,
  total_harvest: number,
  bulls: number,
  cows: number,
  calves: number,
  location: string,
  district_square_mileage: number,
  public_land_percentage: number,
  harvested_bulls_per_square_mile: number,
  harvested_cows_per_square_mile: number,
  harvested_calves_per_square_mile: number,
  total_harvest_per_square_mile: number,
}
