export interface MountainGoat {
  license_year: number,
  district: string,
  residency: string,
  hunters: number,
  days: number,
  days_per_hunter: number,
  total_harvest: number,
  billies: number,
  nannies: number,
  kids: number,
  location: string,
  district_square_mileage: number,
  public_land_percentage: number,
  harvested_billies_per_square_mile: number,
  harvested_nannies_per_square_mile: number,
  harvested_kids_per_square_mile: number,
  total_harvest_per_square_mile: number,
}
